version: '3.8'

services:
  mysql-user:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Namduy2003@))#
      - MYSQL_DATABASE=user_db  # Tạo database cho chat service
    ports:
      - "3309:3306"

  mysql-chat:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Namduy2003@))#
      - MYSQL_DATABASE=chat_db  # Tạo database cho chat service
    ports:
      - "3308:3306"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  eureka-server:
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - eureka-server

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      - SPRING_APPLICATION_NAME=user-service
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  chat-service:
    build:
      context: ./chat-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      - SPRING_APPLICATION_NAME=chat-service
      - EUREKA_CLIENT_SERVICEURL=http://eureka-server:8761/eureka/

